# Generated by Django 4.2.14 on 2024-08-07 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='Слаг')),
                ('body', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='media/blog', verbose_name='Изображение')),
                ('publish', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Опубликовано')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('DF', 'Черновик'), ('PB', 'Опубликовано')], default='DF', max_length=2, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'db_table': 'post',
                'ordering': ['-publish'],
            },
        ),
    ]
