# Generated by Django 4.2.14 on 2024-08-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slag',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=0, max_length=150, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
